from main import fetch_next_matches, generate_ics

def run_update():
    print("Avvio aggiornamento calendario Inter...")
    matches = fetch_next_matches()
    generate_ics(matches)
    print("Aggiornamento completato.")

if __name__ == '__main__':
    run_update()
